name: moodinger
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  dotted_border: ^2.0.0+3
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/users/
    - images/posts/


  fonts:
    - family: GR
      fonts:
        - asset: fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: fonts/GilroyExtraBold.ttf
          weight: 800
          
    - family: GH
      fonts:
        - asset: fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 500
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
